### ISSUE TITLE
Experiment how to host the discord bot

### ISSUE THREAD

**Issue by ZuliusRoolf** [SERLatBTH/discord#2]

**Comment by ZuliusRoolf** [comment]
When using [Discord's official instructions](https://discord.com/developers/docs/quick-start/getting-started) to create a discord bot, they used node js and it would be mandatory to run a server to make the bot functional.
Now that I asked ChatGPT on alternatives and found [`discord.py`](https://discordpy.readthedocs.io/en/stable/index.html#) as a suitable solution, the python library somehow automatically handles the port forwarding and handshakes. So we only need a computer to host it and can skip the server infrastructure.

No idea how secure or how they provide service, but our bot is not supposed to handle sensitive data, so it should be fine.

**Comment by andreas-bauer** [comment]
The project should be containerized to allow to deploy it on different servers and ensure the required dependenciesies.
@ZuliusRoolf If you want me to containerize this application, create a new issue and assign me to it.
